# Use an official MySQL image as a base image
FROM mysql:latest

# Set environment variables (you may customize these)
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root
EXPOSE 3306
